export const AUTH_SIGN_IN_ERRORS = {
    USER_DISABLED: "USER_DISABLED",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    WRONG_PASSWORD: "WRONG_PASSWORD"
};

export const AUTH_SIGN_UP_ERRORS = {
    EMAIL_ALREADY_IN_USE: "EMAIL_ALREADY_IN_USE",
    INVALID_EMAIL: "INVALID_EMAIL",
    OPERATION_NOT_ALLOWED: "OPERATION_NOT_ALLOWED",
    WEAK_PASSWORD: "WEAK_PASSWORD",
    PASSWORDS_NOT_MATCH: "PASSWORDS_NOT_MATCH"
};

